import { z } from "zod";

// ─── Input Schema (what the quiz sends) ─────────────────────────────────────

export const WebsiteGoalEnum = z.enum([
  "get_leads",
  "sell_products",
  "brand_story",
  "get_bookings",
  "showcase_work",
  "build_credibility",
]);

export const WebsiteTypeEnum = z.enum([
  "info_brochure",
  "landing_page",
  "ecommerce",
  "portfolio",
]);

export const StyleTagEnum = z.enum([
  "Modern", "Playful", "Premium", "Bold", "Warm", "Minimal",
  "Technical", "Handcrafted", "Secure", "Trustworthy",
  "Elegant", "Creative", "Tough", "Feminine", "Masculine",
]);

export const TypographyStyleEnum = z.enum([
  "clean_modern",
  "elegant_editorial",
  "technical_bold",
  "friendly_rounded",
  "professional_corporate",
  "ai_suggest",
]);

export const ColorDirectionSchema = z.discriminatedUnion("mode", [
  z.object({
    mode: z.literal("existing"),
    colors: z.object({
      primary:   z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Invalid hex color"),
      secondary: z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Invalid hex color"),
      accent:    z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Invalid hex color"),
    }),
  }),
  z.object({ mode: z.literal("suggest") }),
]);

export const QuizPayloadSchema = z.object({
  business_name: z.string().min(1).max(100),
  products_services: z.string().min(10).max(1500),
  website_goal: z.array(WebsiteGoalEnum).min(1),
  target_customers: z.string().max(500).optional().default(""),
  competitor_urls: z.string().max(500).optional().default(""),
  website_type: WebsiteTypeEnum,
  sitemap: z.object({
    page_count: z.number().int().min(1).max(20),
    pages_description: z.string().max(1000),
  }),
  style_tags: z.array(StyleTagEnum).min(1).max(5),
  color_direction: ColorDirectionSchema,
  typography_style: TypographyStyleEnum,
  email: z.string().email(),
  regenerate_count: z.number().int().min(0).max(2).optional().default(0),
  comments: z.array(z.string()).optional().default([]),
});

export type QuizPayload = z.infer<typeof QuizPayloadSchema>;

// ─── Output Schema (what the LLM must return) ────────────────────────────────

const HexColorSchema = z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Must be a 6-digit hex color");

export const SectionStyleSchema = z.object({
  name: z.string(),
  bg_color: HexColorSchema,
  text_color: HexColorSchema,
  heading_color: HexColorSchema,
  accent_color: HexColorSchema,
  btn_primary_bg: HexColorSchema,
  btn_primary_text: HexColorSchema,
  btn_secondary_border: HexColorSchema,
  btn_secondary_text: HexColorSchema,
});

export const DemoContentSchema = z.object({
  hero: z.object({
    title: z.string(),
    subtitle: z.string(),
    cta_primary: z.string(),
    cta_secondary: z.string()
  }),
  features: z.array(z.object({
    title: z.string(),
    desc: z.string(),
    num: z.string()
  })),
  stats: z.array(z.object({
    value: z.string(),
    label: z.string()
  })),
  cta: z.object({
    title: z.string(),
    subtitle: z.string(),
    button_text: z.string()
  }),
  pricing: z.array(z.object({
    name: z.string(),
    price: z.string(),
    desc: z.string(),
    items: z.array(z.string())
  })),
  faq: z.array(z.object({
    q: z.string(),
    a: z.string()
  })),
  team: z.array(z.object({
    name: z.string(),
    role: z.string(),
    bio: z.string(),
    emoji: z.string()
  })),
  services: z.array(z.object({
    title: z.string(),
    desc: z.string(),
    tag: z.string(),
    emoji: z.string()
  })),
  products: z.array(z.object({
    name: z.string(),
    price: z.string(),
    cat: z.string(),
    rating: z.string(),
    emoji: z.string()
  })),
  testimonials: z.array(z.object({
    quote: z.string(),
    author: z.string()
  })),
  blog: z.array(z.object({
    title: z.string(),
    date: z.string(),
    read: z.string(),
    emoji: z.string()
  }))
});

export const AIOutputSchema = z.object({
  business_name: z.string(),
  colors: z.object({
    primary:                 HexColorSchema,
    secondary:               HexColorSchema,
    accent:                  HexColorSchema,
    background:              HexColorSchema,
    surface:                 HexColorSchema,
    text:                    HexColorSchema,
    text_muted:              HexColorSchema,
    // Explicit Button Palette generated by the Stylist Agent
    btn_primary_bg:          HexColorSchema,
    btn_primary_text:        HexColorSchema,
    btn_hover_primary_bg:    HexColorSchema,
    btn_hover_primary_text:  HexColorSchema,
    btn_secondary_border:    HexColorSchema,
    btn_secondary_text:      HexColorSchema,
    btn_hover_secondary_bg:  HexColorSchema,
    btn_hover_secondary_text:HexColorSchema,
    btn_tertiary_text:       HexColorSchema,
  }),
  typography: z.object({
    heading: z.object({
      family: z.string(),
      weight: z.string(),
      google_font_url: z.string().url(),
    }),
    body: z.object({
      family: z.string(),
      weight: z.string(),
      google_font_url: z.string().url(),
    }),
  }),
  icon_style: z.string().optional().default("duotone-colored"),
  icon_set: z.array(z.object({
    label: z.string(),
    symbol: z.string(),
  })).min(6).max(12),
  sitemap: z.array(z.object({
    slug:     z.string(),
    label:    z.string(),
    sections: z.array(SectionStyleSchema),
  })).min(1),
  demo_content:      DemoContentSchema,
  logo_url:          z.string().optional().nullable(),
  moodboard_images:  z.array(z.string()).optional().default([]),
  hero_image_url:    z.string().optional().nullable(),
  tagline:           z.string().max(200).transform((s) => s.slice(0, 200)),
  vibe_summary:      z.string().max(1000).transform((s) => s.slice(0, 1000)),
});

export type AIOutput = z.infer<typeof AIOutputSchema>;
